# ElastiCache Redis — Terraform Configuration
#
# Companion documentation: ../../docs/15-kubernetes-deployment/
#
# This file provisions the Redis cluster used by the Apollo Router for:
#   1. Entity cache — caches resolved entity objects from subgraphs. Reduces
#      the number of entity fetch requests sent to subgraphs on subsequent
#      queries that include the same entity keys.
#   2. APQ cache (Automatic Persisted Queries) — stores operation documents
#      indexed by their SHA-256 hash. Clients send only the hash on repeat
#      requests, dramatically reducing HTTP payload sizes for large operations.
#
# Resources created:
#   - random_password               — generates the Redis auth token
#   - aws_secretsmanager_secret     — stores the auth token
#   - aws_elasticache_subnet_group  — pins the cluster to private subnets
#   - aws_security_group            — restricts Redis ingress to EKS nodes only
#   - aws_elasticache_replication_group — the Redis cluster itself
#   - aws_cloudwatch_metric_alarm   — CacheMisses and ReplicationLag alarms
#
# Provider requirements: hashicorp/aws ~> 5.30, hashicorp/random ~> 3.6

terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# ---------------------------------------------------------------------------
# Variable declarations
# ---------------------------------------------------------------------------

variable "vpc_id" {
  description = "VPC ID where the Redis cluster and EKS nodes are deployed. Security group rules use this VPC."
  type        = string
}

variable "private_subnet_ids" {
  description = "List of private subnet IDs for the ElastiCache subnet group. Use subnets in at least two AZs for multi-AZ support."
  type        = list(string)
  validation {
    condition     = length(var.private_subnet_ids) >= 2
    error_message = "At least two private subnet IDs are required for multi-AZ Redis."
  }
}

variable "eks_node_security_group_id" {
  description = "Security group ID of the EKS node group. Redis ingress will be allowed from this security group on port 6379."
  type        = string
}

variable "redis_node_type" {
  description = "ElastiCache node type. For production GraphQL entity caching, r7g.large provides a good baseline. See sizing notes in this file."
  type        = string
  default     = "cache.r7g.large"
}

variable "redis_num_replicas" {
  description = "Number of read replicas per shard. 2 replicas in production (1 primary + 2 replicas = 3 nodes total) for high availability."
  type        = number
  default     = 2
  validation {
    condition     = var.redis_num_replicas >= 1
    error_message = "At least one replica is required for automatic_failover_enabled."
  }
}

variable "cloudwatch_alarm_actions" {
  description = "List of ARNs to notify when CloudWatch alarms trigger. Typically an SNS topic ARN for PagerDuty or Slack."
  type        = list(string)
  default     = []
}

# ---------------------------------------------------------------------------
# Auth token: random_password + Secrets Manager
#
# Redis AUTH requires a password between 16 and 128 characters. We use
# random_password to generate a cryptographically secure token at provision
# time and store it immediately in Secrets Manager.
#
# The Apollo Router reads this token from Secrets Manager at startup via the
# IRSA role granted to it in eks-irsa-roles.tf.
# ---------------------------------------------------------------------------

resource "random_password" "redis_auth_token" {
  # 64 characters provides 384 bits of entropy — well above the minimum.
  length = 64

  # Redis AUTH tokens must not contain spaces or these specific characters
  # which conflict with the Redis command parser.
  special          = true
  override_special = "!#$%&*()-_=+[]{}|<>?"

  # Rotations: to rotate the auth token, taint this resource and apply.
  # ElastiCache supports a 2-token rotation window (old token remains valid
  # during rotation). Plan rotation during low-traffic periods.
  #
  # lifecycle.keepers forces regeneration when the cluster ID changes,
  # ensuring a new token on full cluster replacement.
  keepers = {
    cluster_id = "graphql-platform-redis-${var.environment_tag}"
  }
}

resource "aws_secretsmanager_secret" "redis_auth_token" {
  name = "graphql-platform/${var.environment_tag}/redis-auth-token"

  description = "Redis AUTH token for the Apollo Router entity and APQ cache cluster. Generated by Terraform. Rotate by tainting random_password.redis_auth_token."

  # 30-day recovery window in production. Accidentally deleting this secret
  # would take the Apollo Router offline until a new token is provisioned
  # and the Router restarts.
  recovery_window_in_days = 30

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
    Team        = "platform"
  }
}

resource "aws_secretsmanager_secret_version" "redis_auth_token" {
  secret_id     = aws_secretsmanager_secret.redis_auth_token.id
  secret_string = random_password.redis_auth_token.result

  # When the random_password is rotated, Terraform will update this version.
  # During the rotation window, ElastiCache accepts both the old and new tokens
  # if you use the modifying approach (add new token, update cluster, remove old).
  # This lifecycle block prevents Terraform from destroying the secret version
  # before the new one is ready — important for zero-downtime rotation.
  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# Subnet group
#
# The subnet group pins the Redis cluster to private subnets. Redis nodes
# should never be in public subnets. Use subnets in at least two AZs so
# ElastiCache can place the primary and replica in different AZs.
# ---------------------------------------------------------------------------

resource "aws_elasticache_subnet_group" "redis" {
  name = "graphql-platform-redis-${var.environment_tag}"

  description = "Private subnets for Apollo Router Redis cache cluster. Multi-AZ placement for high availability."

  # Use the private subnets passed from the VPC module. These subnets should
  # have no internet gateway route — Redis should never be reachable from outside
  # the VPC.
  subnet_ids = var.private_subnet_ids

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
  }
}

# ---------------------------------------------------------------------------
# Security group: Redis
#
# Allow ingress on port 6379 exclusively from the EKS node security group.
# All other inbound connections are implicitly denied.
#
# Do NOT allow 0.0.0.0/0 ingress on port 6379 under any circumstances.
# Redis has historically had critical vulnerabilities triggered by unauthenticated
# connections, and even with AUTH enabled, reducing network attack surface is
# always the right call.
# ---------------------------------------------------------------------------

resource "aws_security_group" "redis" {
  name        = "graphql-platform-redis-${var.environment_tag}"
  description = "Security group for the Apollo Router Redis cache. Allows ingress from EKS nodes only."

  # Associate with the VPC containing both EKS and ElastiCache resources.
  vpc_id = var.vpc_id

  # Ingress: allow Redis protocol traffic from EKS nodes.
  # Using source_security_group_id instead of a CIDR block means the rule
  # automatically tracks EKS nodes even as their IP addresses change.
  ingress {
    description     = "Redis from EKS nodes"
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [var.eks_node_security_group_id]
  }

  # Egress: allow all outbound traffic.
  # ElastiCache nodes need to communicate with each other for cluster coordination
  # and with AWS internal endpoints for monitoring. Restricting egress provides
  # minimal security benefit here and complicates cluster management.
  egress {
    description = "Allow all outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
  }

  lifecycle {
    # Create a new security group before destroying the old one to avoid
    # a window where the cluster has no security group and is unreachable.
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# ElastiCache Replication Group (Redis 7.x, Cluster Mode)
#
# SIZING RATIONALE for cache.r7g.large:
#
# Apollo Router entity cache behavior:
#   - Entities are serialized JSON objects keyed by (type, id) pairs
#   - A typical entity object (User, Product, Order) is 500 bytes - 5 KB
#   - A production federated graph often has 50k-500k distinct entities in cache
#   - At 1 KB avg, 500k entities = ~500 MB of entity cache data
#   - Add 30% overhead for Redis internal data structures and key metadata
#   - Working set: ~650 MB
#
# APQ cache behavior:
#   - An APQ entry is (SHA-256 hash, full query document)
#   - A typical operation is 1-5 KB; a mobile app might have 200-500 operations
#   - At 3 KB avg, 500 operations = 1.5 MB — negligible
#
# r7g.large provides 13.07 GB memory.
# This leaves ample headroom for the ~700 MB entity cache working set,
# supports traffic spikes where cache fills temporarily above steady state,
# and provides room for Redis internal overhead.
#
# For staging: cache.t4g.medium (3.09 GB) is sufficient and cost-effective.
# Scale up to r7g.xlarge (26.32 GB) if entity count exceeds ~5 million.
# ---------------------------------------------------------------------------

resource "aws_elasticache_replication_group" "redis" {
  # replication_group_id is the stable identifier used in endpoint URLs.
  # Keep it short and descriptive — it appears in the primary endpoint hostname.
  replication_group_id = "graphql-platform-redis-${var.environment_tag}"

  description = "Apollo Router entity cache and APQ cache. Cluster mode with multi-AZ automatic failover."

  # Redis 7.x is required for the latest performance improvements and for
  # RDB + AOF persistence configuration options. Redis 7 also includes
  # improved memory efficiency for hash structures used by the entity cache.
  engine_version = "7.1"

  # Node type — see sizing rationale in the block comment above.
  node_type = var.redis_node_type

  # Port 6379 is the standard Redis port.
  port = 6379

  # num_cache_clusters sets the total number of nodes (primary + replicas) in
  # the replication group when cluster_mode is disabled.
  # With cluster_mode_enabled = true, use num_node_groups and
  # replicas_per_node_group instead.
  # We use a single shard (1 node group) because the Apollo Router entity cache
  # does not benefit from hash-slot sharding — the workload is evenly distributed
  # by entity key hashing within a single shard.
  num_cache_clusters = var.redis_num_replicas + 1  # primary + replicas

  # automatic_failover_enabled promotes a read replica to primary automatically
  # when the primary node fails. This reduces downtime from minutes (manual
  # failover) to seconds (automated promotion).
  # Requires num_cache_clusters >= 2 (at least one replica).
  automatic_failover_enabled = true

  # multi_az_enabled places the primary and at least one replica in different
  # Availability Zones. When combined with automatic_failover_enabled, a full
  # AZ failure triggers replica promotion in the surviving AZ.
  multi_az_enabled = true

  # subnet_group_name pins the cluster to private subnets defined above.
  subnet_group_name = aws_elasticache_subnet_group.redis.name

  # security_group_ids attaches the Redis security group that allows ingress
  # only from EKS nodes.
  security_group_ids = [aws_security_group.redis.id]

  # auth_token enables Redis AUTH. Clients must send the token with every
  # connection. The token is 64 characters generated by random_password above.
  # transit_encryption_enabled must be true when auth_token is set.
  auth_token = random_password.redis_auth_token.result

  # transit_encryption_enabled encrypts data in transit between the Apollo
  # Router and Redis. Required when auth_token is used. Uses TLS 1.2+.
  transit_encryption_enabled = true

  # at_rest_encryption_enabled encrypts the Redis RDB snapshots stored in S3
  # and the in-memory data (when snapshots are taken). Uses AES-256.
  at_rest_encryption_enabled = true

  # snapshot_retention_limit is the number of days to retain daily snapshots.
  # 7 days provides recovery capability for accidental data corruption.
  # 0 disables snapshots — do not use 0 in production even for cache clusters,
  # because entity cache warming after a cold start can spike subgraph load.
  snapshot_retention_limit = 7

  # snapshot_window is the UTC time window for daily snapshots.
  # Choose a low-traffic window. Apollo Router traffic is typically lowest
  # between 03:00 and 05:00 UTC for US-centric applications.
  snapshot_window = "03:00-05:00"

  # maintenance_window is when ElastiCache applies minor version patches
  # and replacement events. Keep this outside peak hours.
  maintenance_window = "sun:05:00-sun:06:00"

  # apply_immediately controls whether minor setting changes take effect
  # immediately or at the next maintenance window.
  # false is safer for production — changes are batched with other maintenance
  # to reduce disruption frequency.
  apply_immediately = false

  # log_delivery_configuration ships Redis slow logs and engine logs to
  # CloudWatch Logs for query analysis and debugging.
  log_delivery_configuration {
    destination      = "/aws/elasticache/graphql-platform-redis-${var.environment_tag}/slow-logs"
    destination_type = "cloudwatch-logs"
    log_format       = "json"  # json format is machine-parseable for log analysis
    log_type         = "slow-log"
  }

  log_delivery_configuration {
    destination      = "/aws/elasticache/graphql-platform-redis-${var.environment_tag}/engine-logs"
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "engine-log"
  }

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
    Team        = "platform"
    # CostCenter tag enables Redis cost attribution in AWS Cost Explorer.
    # This is important because cache.r7g.large instances are non-trivial cost.
    CostCenter  = "graphql-platform"
  }

  lifecycle {
    # Prevent accidental destruction of the production Redis cluster.
    # To replace the cluster (e.g., for a major version upgrade requiring
    # a blue/green approach), remove this block temporarily, apply, then
    # re-add it after the new cluster is confirmed healthy.
    prevent_destroy = true
  }

  depends_on = [
    aws_elasticache_subnet_group.redis,
    aws_security_group.redis,
    aws_secretsmanager_secret_version.redis_auth_token,
  ]
}

# ---------------------------------------------------------------------------
# CloudWatch Metric Alarms
#
# Two alarms cover the most critical Redis health indicators for an Apollo
# Router entity cache:
#
# 1. CacheMisses — high miss rate means entities are not being served from
#    cache. Either the TTL is too short, the cache is too small for the working
#    set, or there is a cache invalidation bug. A miss rate above 80% indicates
#    the cache is providing little benefit and subgraph load is elevated.
#
# 2. ReplicationLag — the replica is falling behind the primary. High replication
#    lag means a failover would promote a stale replica, causing clients to
#    temporarily read outdated entity data until replication catches up.
# ---------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "redis_cache_misses" {
  alarm_name = "graphql-platform-redis-${var.environment_tag}-high-cache-misses"

  alarm_description = "Redis cache miss rate is above 80%. Entity cache is not serving traffic effectively. Check TTL configuration, cache size, and entity invalidation logic in the Apollo Router configuration."

  # Namespace and metric name for ElastiCache Redis metrics.
  namespace   = "AWS/ElastiCache"
  metric_name = "CacheMisses"

  # Dimensions identify the specific replication group.
  dimensions = {
    ReplicationGroupId = aws_elasticache_replication_group.redis.id
  }

  # Statistics
  statistic           = "Sum"
  period              = 300   # 5-minute evaluation windows smooth out momentary spikes
  evaluation_periods  = 3     # require 3 consecutive 5-minute windows above threshold

  # Threshold: 80% miss rate.
  # CacheMisses is an absolute count, not a percentage. We alarm when misses
  # are elevated in absolute terms — adjust threshold based on your traffic volume.
  # For a 1000 req/s workload with 5-minute windows: 1000 * 300 = 300,000 requests.
  # 80% miss rate = 240,000 misses per period.
  # Start with a lower threshold and tune based on observed baseline.
  threshold           = 240000
  comparison_operator = "GreaterThanThreshold"

  # treat_missing_data as "notBreaching" prevents false alarms when the
  # cluster is briefly unreachable or metrics are delayed.
  treat_missing_data = "notBreaching"

  # alarm_actions and ok_actions should point to an SNS topic that
  # routes to the on-call rotation.
  alarm_actions = var.cloudwatch_alarm_actions
  ok_actions    = var.cloudwatch_alarm_actions

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
  }
}

resource "aws_cloudwatch_metric_alarm" "redis_replication_lag" {
  alarm_name = "graphql-platform-redis-${var.environment_tag}-high-replication-lag"

  alarm_description = "Redis replication lag exceeds 1 second. A failover would promote a stale replica. Investigate primary node CPU, network throughput, and write throughput."

  namespace   = "AWS/ElastiCache"
  metric_name = "ReplicationLag"

  dimensions = {
    ReplicationGroupId = aws_elasticache_replication_group.redis.id
  }

  # ReplicationLag is reported in seconds.
  statistic           = "Maximum"  # use Maximum not Average — we want to catch worst-case
  period              = 60         # 1-minute windows for faster detection of replication issues
  evaluation_periods  = 3          # 3 consecutive 1-minute windows = 3 minutes of sustained lag

  threshold           = 1.0        # 1 second lag threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  alarm_actions = var.cloudwatch_alarm_actions
  ok_actions    = var.cloudwatch_alarm_actions

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
  }
}

resource "aws_cloudwatch_metric_alarm" "redis_freeable_memory" {
  alarm_name = "graphql-platform-redis-${var.environment_tag}-low-freeable-memory"

  alarm_description = "Redis freeable memory is below 1 GB. The entity cache working set may be exceeding node capacity. Consider upgrading to cache.r7g.xlarge or reducing entity cache TTLs."

  namespace   = "AWS/ElastiCache"
  metric_name = "FreeableMemory"

  dimensions = {
    ReplicationGroupId = aws_elasticache_replication_group.redis.id
  }

  statistic           = "Minimum"   # alert when any node is low on memory
  period              = 300
  evaluation_periods  = 2

  # 1 GB = 1,073,741,824 bytes
  # Below 1 GB of freeable memory on a r7g.large (13 GB) means >92% utilization.
  # This is the point at which Redis eviction policy starts removing keys and
  # cache hit rates degrade.
  threshold           = 1073741824
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "notBreaching"

  alarm_actions = var.cloudwatch_alarm_actions
  ok_actions    = var.cloudwatch_alarm_actions

  tags = {
    Environment = var.environment_tag
    ManagedBy   = "terraform"
    Service     = "elasticache-redis"
  }
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

output "redis_primary_endpoint" {
  description = "Primary endpoint URL for Redis write operations. Use in Apollo Router entity_cache.redis configuration."
  value       = aws_elasticache_replication_group.redis.primary_endpoint_address
}

output "redis_reader_endpoint" {
  description = "Reader endpoint URL for Redis read operations (round-robins across replicas). Use for read-heavy cache operations if the Router supports a separate reader endpoint."
  value       = aws_elasticache_replication_group.redis.reader_endpoint_address
}

output "redis_port" {
  description = "Redis port (6379). Always 6379 for standard Redis; include in connection URL."
  value       = aws_elasticache_replication_group.redis.port
}

output "redis_auth_token_secret_arn" {
  description = "ARN of the Secrets Manager secret holding the Redis AUTH token. Used in the Apollo Router IRSA policy to grant access."
  value       = aws_secretsmanager_secret.redis_auth_token.arn
}

output "redis_security_group_id" {
  description = "Security group ID attached to the Redis cluster. Add this as an ingress rule source if deploying additional services that need Redis access."
  value       = aws_security_group.redis.id
}

output "redis_replication_group_id" {
  description = "The ElastiCache replication group ID. Use to reference this cluster in other Terraform resources and in CloudWatch dashboards."
  value       = aws_elasticache_replication_group.redis.id
}
